#!/bin/bash
echo \<script type=\"text/javascript\"\>
echo var radiodrama = {
echo     program_infix: \"$1\",
echo     episodes: $2,
echo     digit: $3
echo };
echo \</script\>
echo \<script type=\'text/javascript\' src=\"app.js\"\>\</script\>
echo \</body\>
echo \</html\>
